spring.application.name=student-information-system-service

spring.datasource.url=jdbc:sqlserver://localhost:1434;instanceName=SQLExpress01;databaseName=student_information_system_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=best_in_Me0909
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.flyway.default-schema=my_schema

jwt.secretkey=rowel_secret_key_23292ha9djw93jd